[workspace]
members = [
    "sv-parser",
    "sv-parser-syntaxtree",
    "sv-parser-parser",
    "sv-parser-macros",
]

[patch.crates-io]
nom_locate = {git = "https://github.com/fflorent/nom_locate"}
