[package]
name = "sv-parser-syntaxtree"
version = "0.1.0"
authors = ["dalance <dalance@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
sv-parser-macros = { path = "../sv-parser-macros" }

[build-dependencies]
walkdir = "2"
regex = "1"
