[package]
name = "sv-parser-parser"
version = "0.1.0"
authors = ["dalance <dalance@gmail.com>"]
edition = "2018"

[features]
default = []
trace   = ["nom-tracable/trace"]

[dependencies]
nom                  = "5.0.0"
nom_locate           = "0.4.0"
nom-packrat          = {path = "../../nom-packrat/nom-packrat"}
nom-recursive        = {path = "../../nom-recursive/nom-recursive"}
nom-tracable         = {path = "../../nom-tracable/nom-tracable"}
str-concat           = "*"
sv-parser-macros     = {path = "../sv-parser-macros"}
sv-parser-syntaxtree = {path = "../sv-parser-syntaxtree"}
