[package]
name = "sv-parser-parser"
version = "0.4.14"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/sv-parser"
keywords = ["parser", "verilog", "systemverilog"]
categories = ["parsing"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "Helper crate of sv-parser"
edition = "2018"

[package.metadata.release]
disable-tag = true

[features]
default = []
trace   = ["nom-tracable/trace"]

[dependencies]
nom                  = "5.0.0"
nom_locate           = "1.0.0"
nom-greedyerror      = "0.1.0"
nom-packrat          = "0.3.0"
nom-recursive        = {version = "0.1.1", features = ["tracer128"]}
nom-tracable         = "0.4.1"
str-concat           = "0.1.4"
sv-parser-macros     = {version = "^0.4.14", path = "../sv-parser-macros"}
sv-parser-syntaxtree = {version = "^0.4.14", path = "../sv-parser-syntaxtree"}
