[package]
name = "sv-parser-macros"
version = "0.1.0"
authors = ["dalance <dalance@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "0.6.9"
syn   = { version = "0.15.18", features = ["full", "fold", "parsing", "extra-traits"] }
