[package]
name = "sv-parser-pp"
version = "0.1.0"
authors = ["dalance@gmail.com"]
repository = "https://github.com/dalance/sv-parser"
keywords = ["parser", "verilog", "systemverilog"]
categories = ["parsing"]
license = "MIT OR Apache-2.0"
readme = "../README.md"
description = "Helper crate of sv-parser"
edition = "2018"

[features]
default = []
trace   = ["sv-parser-parser/trace"]

[dependencies]
failure              = "0.1.5"
nom                  = "5.0.0"
sv-parser-error      = { path = "../sv-parser-error" }
sv-parser-parser     = { path = "../sv-parser-parser" }
sv-parser-syntaxtree = { path = "../sv-parser-syntaxtree" }
