name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: juankaram/rust-musl-action@master
    - name: Build
      run: cargo build --target x86_64-unknown-linux-musl --release --example parse_sv
